Repository wix/react-native-calendars, pull requests merged in 2020-12, with the labels that each got.

#1344 Fix day text align on multi-period (modified)
  src/calendar/day/multi-period/index.js
  src/calendar/day/multi-period/style.js
Labels: merge-candidate

#1334 added callback on toggling expandable calendar
  src/expandableCalendar/index.js
Labels: Pending, Wix, merge-candidate

#1300 Fixed startingDate and endingDate style
  src/calendar/day/period/index.js
Labels: Pending
