Repository wix/react-native-calendars, pull requests merged in 2022-03, with the labels that each got.

#1814 Fix - Adding missing dependencies to callbacks
  src/calendar/day/basic/index.tsx
  src/calendar/header/index.tsx
Labels: FIX

#1818 Agenda - fix for 'selected' as undefined
  src/agenda/index.tsx
Labels: FIX

#1812 Support Timeline unavailableHours
  example/src/screens/timelineCalendar.tsx
  src/timeline/Packer.ts
  src/timeline/Timeline.tsx
  src/timeline/TimelineHours.tsx
  src/timeline/__tests__/Packer.spec.js
  src/timeline/style.ts
Labels: Important for next release

#1811 Migrate to functional components - 2
  example/src/screens/calendars.tsx
  example/src/screens/expandableCalendar.tsx
  example/src/screens/horizontalCalendarList.tsx
  src/calendar/day/period/index.tsx
  src/calendar/day/period/style.ts
  src/calendar/index.tsx
Labels: Important for next release

#1834 Day - fix date prop's return type for 'dayComponent'
  src/calendar/day/index.tsx
Labels: Important for next release

#1847 Agenda - BUG fix - onDayPress triggering additional day reset
  src/agenda/index.tsx
Labels: FIX, Important for next release
